### ISSUE TITLE
Default Config Exception on startup

### ISSUE THREAD

**Issue by cawalch** [neoclide/coc-eslint#1]
I've been unable to get `coc-eslint` to report linting errors/warnings. Here is my `workstation.showOutput` output. Any ideas?

```
 [Trace - 10:29:10] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
  Result: [
      {
          "packageManager": "npm",
          "validate": true,
          "autoFix": true,
          "autoFixOnSave": false,
          "options": {},
          "run": "onType",
          "workspaceFolder": {
              "uri": "file:///home/cawalch/foo",
              "name": "foo"
          }
      }
  ]


  [Trace - 10:29:10] Received notification 'window/logMessage'.
  Params: {
      "type": 3,
      "message": "Registering request handler for workspace/didChangeWorkspaceFolders failed."
  }


  [1  - 10:29:10] Registering request handler for workspace/didChangeWorkspaceFolders failed.
  (node:55260) UnhandledPromiseRejectionWarning: Error: Request client/registerCapability failed with message: No feature implementation for workspace/didChangeWorkspaceFolders found. Registration failed.
      at handleResponse (/home/cawalch/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/main.js:436:48)
      at processMessageQueue (/home/cawalch/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/main.js:263:17)
      at Immediate.setImmediate [as _onImmediate] (/home/cawalch/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/main.js:247:13)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
  (node:55260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
  (node:55260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  [Trace - 10:29:11] 'npm config get prefix' value is: /home/cawalch/.nvm/versions/node/v8.10.0
  [Trace - 10:29:11] NODE_PATH value is: /home/cawalch/.nvm/versions/node/v8.10.0/lib/node_modules
  module.js:547
      throw err;
      ^

  Error: Cannot find module '-e'
      at Function.Module._resolveFilename (module.js:545:15)
      at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
      at Function.Module._load (module.js:472:25)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
      at startup (bootstrap_node.js:227:16)
      at bootstrap_node.js:648:3
```

**Comment by chemzqm** [comment]
Looks like you're using old version of coc-eslint, try command `:CocUpdate` in your vim.

**Comment by cawalch** [comment]
I did a fresh install and ran into the same issue.

 I was able to get working by installing from source `{'do': 'yarn install'}`.
