### ISSUE TITLE
Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by Achill113** [neoclide/coc-eslint#124]
I just set up NeoVim with coc and I am adding coc-eslint. When trying to run eslint on my project I am receiving the following error.

`Error: Request workspace/configuration failed with message: Cannot read properties of null (reading 'name')
    at handleResponse (C:\Users\alex.hill\AppData\Local\coc\extensions\node_modules\coc-eslint\lib\server.js:2098:38)
    at processMessageQueue (C:\Users\alex.hill\AppData\Local\coc\extensions\node_modules\coc-eslint\lib\server.js:1923:11)
    at Immediate.<anonymous> (C:\Users\alex.hill\AppData\Local\coc\extensions\node_modules\coc-eslint\lib\server.js:1909:9)
    at processImmediate (node:internal/timers:464:21)`

undefined## versions

vim version: NVIM v0.6.1
node version: v16.13.2
coc.nvim version: 0.0.80-452671ce30
coc.nvim directory: C:\Users\alex.hill\AppData\Local\nvim\plugged\coc.nvim
term: vtpcon
platform: win32

**Comment by chemzqm** [comment]
Seems you're not using latest coc-eslint.

**Comment by Achill113** [comment]
@chemzqm thank you for the quick fix, much appreciated. ❤️
