### ISSUE TITLE
UnhandledRejection opening markdown files

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-eslint#135]
Recently anytime I'm opening standalone markdown files (e.g. `nvim /tmp/foo.md`), I'm getting this error:

```
[coc.nvim]: UnhandledRejection: Request textDocument/codeAction failed with message: No ESLint configuration found in /tmp.
Error: Request textDocument/codeAction failed with message: No ESLint configuration found in /tmp.
    at Ie (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:29:233)
    at Bi (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6872)
    at Immediate.<anonymous> (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6719)
    at process.processImmediate (node:internal/timers:471:21)
```

**Comment by fannheyward** [comment]
I can't reproduce this, any more infos?

**Comment by oblitum** [comment]
`:CocInfo` gives:

```
## versions

vim version: NVIM v0.7.2
node version: v18.8.0
coc.nvim version: 0.0.82-6da029c4 2022-08-24 22:58:55 +0800
coc.nvim directory: /home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-08-24T22:41:20.269 ERROR (pid:34006) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-08-24T22:41:20.269 ERROR (pid:34006) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-08-24T22:41:20.367 INFO (pid:34006) [services] - registered service "languageserver.graphql"
2022-08-24T22:41:20.367 INFO (pid:34006) [services] - registered service "languageserver.haskell"
2022-08-24T22:41:20.367 INFO (pid:34006) [services] - registered service "languageserver.rescript"
2022-08-24T22:41:20.367 INFO (pid:34006) [services] - registered service "languageserver.bash"
2022-08-24T22:41:20.367 INFO (pid:34006) [services] - registered service "languageserver.purescript"
2022-08-24T22:41:20.368 INFO (pid:34006) [services] - registered service "languageserver.csharp-ls"
2022-08-24T22:41:20.384 INFO (pid:34006) [services] - registered service "diagnostic-languageserver"
2022-08-24T22:41:20.406 INFO (pid:34006) [services] - registered service "eslint"
2022-08-24T22:41:20.416 INFO (pid:34006) [services] - ESLint state change: stopped => starting
2022-08-24T22:41:20.429 INFO (pid:34006) [coc-git] - Looking for git in: git
2022-08-24T22:41:21.341 INFO (pid:34006) [plugin] - coc.nvim initialized with node: v18.8.0 after 1141ms
2022-08-24T22:41:21.353 INFO (pid:34006) [attach] - receive notification: diagnosticRefresh []
2022-08-24T22:41:21.381 INFO (pid:34006) [language-client-index] - Language server "ltex" started with 34070
2022-08-24T22:41:21.440 INFO (pid:34006) [services] - ESLint state change: starting => running
2022-08-24T22:41:21.445 INFO (pid:34006) [services] - service eslint started
2022-08-24T22:41:21.934 ERROR (pid:34006) [events] - Error on event: CursorHold Error: Request textDocument/codeAction failed with message: No ESLint configuration found in /home/francisco.
    at Ie (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:29:233)
    at Bi (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6872)
    at Immediate.<anonymous> (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6719)
    at process.processImmediate (node:internal/timers:471:21)
2022-08-24T22:41:23.477 ERROR (pid:34006) [server] - unhandledRejection  Promise {
  <rejected> Dy [Error]: Request textDocument/codeAction failed with message: No ESLint configuration found in /home/francisco.
      at Ie (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:29:233)
      at Bi (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6872)
      at Immediate.<anonymous> (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6719)
      at process.processImmediate (node:internal/timers:471:21) {
    code: -32603,
    data: undefined
  }
} Dy [Error]: Request textDocument/codeAction failed with message: No ESLint configuration found in /home/francisco.
    at Ie (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:29:233)
    at Bi (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6872)
    at Immediate.<anonymous> (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6719)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: undefined
}
2022-08-24T22:41:25.932 INFO (pid:34006) [attach] - receive notification: diagnosticRefresh []
2022-08-24T22:41:25.936 ERROR (pid:34006) [events] - Error on event: CursorHold Error: Request textDocument/codeAction failed with message: No ESLint configuration found in /home/francisco.
    at Ie (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:29:233)
    at Bi (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6872)
    at Immediate.<anonymous> (/home/francisco/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:28:6719)
    at process.processImmediate (node:internal/timers:471:21)
2022-08-24T22:41:28.415 INFO (pid:34006) [attach] - receive notification: showInfo []
```

**Comment by oblitum** [comment]
As an unrelated note:

```
2022-08-24T22:41:20.269 ERROR (pid:34006) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-08-24T22:41:20.269 ERROR (pid:34006) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
```

No idea why is that, possibly coming from coc-clangd's internal configuration.

**Comment by oblitum** [comment]
I have this eslint configuration:

```
                eslint = {
                    quiet          = true,
                    packageManager = 'yarn'
                },
```

**Comment by fannheyward** [comment]
> Invalid configuration

extensions shouldn't overwrite configurations, coc-clangd has removed theses.

**Comment by fannheyward** [comment]
> CursorHold Error: Request textDocument/codeAction failed

Looks like on `CursorHold` will fetch code actions, tested with markdown + coc-eslint, can't reproduce this, still checking on this.

**Comment by oblitum** [comment]
> > Invalid configuration
> 
> extensions shouldn't overwrite configurations, coc-clangd has removed theses.

Ok, then that's due to no newer release yet.

**Comment by oblitum** [comment]
I may try to reduce to a minimal init, but I'll potentially eliminate the CursorHold cause maybe... I'm short on time at the moment so I can only add this later.

**Comment by chemzqm** [comment]
It's expected error message, use `silent!` with `CocAction` to avoid

**Comment by oblitum** [comment]
But I simply ignore where the `CocAction` call comes from, I don't have any custom `CursorHold` setting.

**Comment by oblitum** [comment]
Oh, I have just one... let me check.

**Comment by oblitum** [comment]
I just removed the single `CursorHold` I had in my init, issue still present.

**Comment by chemzqm** [comment]
You have some coc extension automatically requesting code actions, and it not handles the rejection.

**Comment by oblitum** [comment]
Well... then I'll have to bisect that.

**Comment by chemzqm** [comment]
Seems coc-lightbulb

**Comment by oblitum** [comment]
> Seems coc-lightbulb

What's that? Magic?

Yes, it's that one.

**Comment by oblitum** [comment]
I'll open an issue there.

**Comment by chemzqm** [comment]
But the error should be catched, don't why it throws

**Comment by chemzqm** [comment]
Can't reproduce your issue, the code action request should not send at all.

**Comment by oblitum** [comment]
So it seems very complex to find the culprit.

**Comment by chemzqm** [comment]
I see, the error you get is not from `CursorHold`, but the timer 
```
  setTimeout(async () => {
    await lightbulb.refresh();
  }, 3000);
```
the `CodeActionManager` could be improved to handle the error.

**Comment by oblitum** [comment]
@chemzqm thx, it's fixed.
