### ISSUE TITLE
coc-eslint doesn't work

### ISSUE THREAD

**Issue by cvlmtg** [neoclide/coc-eslint#2]
I've installed coc-eslint but I'm not receiving any output from it. I am using the latest nvim built with homebrew, and I have `.elintrc.js` in the root of the project I'm working on and `eslint` is installed as a dependency of the project. the root of the projects is also the cwd, so I have put these lines in my `~/.config/nvim/coc-settings.json`

```
  "eslint.enable": true,
  "eslint.trace.server": "verbose",
  "eslint.nodePath": "./node_modules/",
  "eslint.options": {
    "configFile": "./.eslintrc.js"
  }
```

and this is part of the output of `CocCommand workspace.showOutput`:

```
[Trace - 08:59:50] NODE_PATH value is: /Users/matteo/dev/html5-exercises-player/node_modules/
[Trace - 08:59:50] NODE_PATH value is: /Users/matteo/.nvf/installed/node-8.12.0/lib/node_modules
Uncaught exception recevied.
Error: spawn /Users/matteo/.config/nvim/plugged/coc.nvim/build/coc-macos ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
module.js:547
    throw err;
    ^

Error: Cannot find module '-e'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
```

the NODE_PATH are correct, and the coc-macos file exists:

```
 ~ ls -l /Users/matteo/.config/nvim/plugged/coc.nvim/build/coc-macos
-rwxr-xr-x  1 matteo  staff  47223252 28 Ott 23:28 /Users/matteo/.config/nvim/plugged/coc.nvim/build/coc-macos
 ```

**Comment by chemzqm** [comment]
Seems issue exist with binary coc, but not when build from source code.

**Comment by chemzqm** [comment]
The Files module from `vscode-languageserver` has problem with binary build with pkg, I've changed to use `resolve-from` module to resolve this bug.

**Comment by chemzqm** [comment]
Run `:CocUpdate` to fix this problem.
