### ISSUE TITLE
Broken path generation (on macvim)

### ISSUE THREAD

**Issue by wonnage** [neoclide/coc-eslint#24]
This plugin works fine on commandline vim. However, it seems like when run it inside MacVim it seems like the file:/// uri is missing the home directory prefix. It results in a crash when trying to open a nonexistent file.

I added a log to print out the URLs that coc-eslint is receiving right before this line: https://github.com/neoclide/coc-eslint/blob/c8f1639146748b46f871144ed471c44741492c97/server/index.ts#L866

Commandline vim log:
````
## Output channel: eslint

[Info  - 12:29:16 PM] ESLint server running in node v10.16.0
[Info  - 12:29:17 PM] ESLint library loaded from: /Users/wonnage/workspace/nbreader/node_modules/eslint/lib/api.js
>>> { uri: 'file:///Users/wonnage/workspace/nbreader',
  name: 'nbreader' } <<<
````

Macvim log:
````
## Output channel: eslint

[Info  - 12:29:36 PM] ESLint server running in node v10.16.0
[Info  - 12:29:37 PM] ESLint library loaded from: /Users/wonnage/workspace/nbreader/node_modules/eslint/lib/api.js
>>> { uri: 'file:///workspace/nbreader/', name: 'nbreader' } <<<
[Error  - 12:29:37 PM] ESLint stack trace:
[Error  - 12:29:37 PM] Error: ENOENT: no such file or directory, chdir '/workspace/nbreader/'
    at process.chdir (internal/process/main_thread_only.js:31:12)
    at validate (/Users/wonnage/.config/coc/extensions/node_modules/coc-eslint/lib/server.js:5509:29)
    at resolveSettings.then.settings (/Users/wonnage/.config/coc/extensions/node_modules/coc-eslint/lib/server.js:5454:13)
````

**Comment by wonnage** [comment]
I actually think this an issue in coc itself, closing
