### ISSUE TITLE
server errors echoed even with silent even with  "eslint.quiet": true

### ISSUE THREAD

**Issue by davidsu** [neoclide/coc-eslint#96]
First of all, I want to thank you again for the amazing work.

Jumping around in my filesystem I keep getting `Environment key "jest/globals" is unknown`
Looks like I'm jumping into `node_modules` folders where `devdependecies` aren't installed(just a guess)

I ended up hacking `autoload/coc/util.vim -> coc#util#echo_messages` to filter out all `Eslint` messages, would be nicer to not have to do that.

follows output for `CocCommand workspace.showOuptup`

```
[Info  - 3:00:00 PM] ESLint server running in node v14.15.3
[Info  - 3:00:01 PM] ESLint library loaded from: /Users/david.susskind/.dotfiles/config/nvim/plugged/coc.nvim/node_modules/eslint/lib/api.js
[Info  - 3:50:29 PM] ESLint library loaded from: /Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/eslint/lib/api.js
[Error  - 3:50:30 PM] ESLint stack trace:
[Error  - 3:50:30 PM] Error: config/nvim/plugged/coc-explorer/node_modules/coc.nvim/.eslintrc.js:
	Environment key "jest/globals" is unknown

    at /Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:173:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:167:34)
    at ConfigValidator.validateConfigArray (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:317:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at CLIEngine.isPathIgnored (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/eslint/lib/cli-engine/cli-engine.js:972:18)
    at CLIEngine.executeOnText (/Users/david.susskind/.dotfiles/config/nvim/plugged/coc-explorer/node_modules/eslint/lib/cli-engine/cli-engine.js:883:38)
    at /Users/david.susskind/.dotfiles/config/coc/extensions/node_modules/coc-eslint/lib/server.js:5928:28
    at Object.executeInWorkspaceDirectory (/Users/david.susskind/.dotfiles/config/coc/extensions/node_modules/coc-eslint/lib/server.js:8963:16)
```

**Comment by GopherJ** [comment]
@davidsu is [this](https://github.com/neoclide/coc-eslint/pull/93) what you need?

**Comment by davidsu** [comment]
Yes, that's perfect.

**Comment by chemzqm** [comment]
`quiet` only avoid warings.
